const documents = [
    {
        id: 1,
        file_name: "AnnualReport2023.pdf",
        size: 1284710,
        status: "Running",
        speed: "12 MB/s",
    },
    {
        id: 2,
        file_name: "SalesData.xlsx",
        size: 2378100,
        status: "Suspended",
        speed: "8 MB/s",
    },
    {
        id: 3,
        file_name: "ProjectPlan.docx",
        size: 1023910,
        status: "Complete",
        speed: "15 MB/s",
    },
    {
        id: 4,
        file_name: "MeetingNotes.txt",
        size: 1547892,
        status: "Incomplete",
        speed: "10 MB/s",
    },
    {
        id: 5,
        file_name: "BudgetProposal.pptx",
        size: 1874590,
        status: "Running",
        speed: "13 MB/s",
    },
    {
        id: 6,
        file_name: "MarketingStrategy.pdf",
        size: 1273804,
        status: "Suspended",
        speed: "11 MB/s",
    },
    {
        id: 7,
        file_name: "EmployeeList.csv",
        size: 2048710,
        status: "Complete",
        speed: "16 MB/s",
    },
    {
        id: 8,
        file_name: "ClientContracts.zip",
        size: 984572,
        status: "Incomplete",
        speed: "9 MB/s",
    },
    {
        id: 9,
        file_name: "ProductCatalog.pdf",
        size: 1483921,
        status: "Running",
        speed: "14 MB/s",
    },
    {
        id: 10,
        file_name: "TrainingMaterial.docx",
        size: 1327498,
        status: "Suspended",
        speed: "7 MB/s",
    },
    {
        id: 11,
        file_name: "User_Doc_Test.docx",
        size: 1327498,
        status: "Waiting",
        speed: "70 MB/s",
    }, {
        id: 12,
        file_name: "TrainingMaterial_w&b.docx",
        size: 1327498,
        status: "Waiting",
        speed: "17 MB/s",
    },
];

export default documents;
